### ISSUE TITLE
Third Chapter Problem with Layout

### ISSUE THREAD

**Issue by domi1210** [PIX3LFLUX/HSK-Latex-Skript-Template#1]
Hi,
as seen in the picture added. When I add a third chapter the roman number 3 is to far left. It should be more to the right. It's not good readable like this.
The number 4 looks fine again.

![image](https://user-images.githubusercontent.com/64898596/180164691-b195ddf6-c7e9-4597-8f99-e6ca99e919bc.png)

**Comment by domi1210** [comment]
If the name gets even longer than "Implementierung" it doesn't start a new line automatically 

![image](https://user-images.githubusercontent.com/64898596/180193252-a7f06243-35fa-4645-be6c-b96a1db4bf66.png)

**Comment by haotruongnhat** [comment]
It's been a while, but here you are.

In `structure.tex`, we shift the part number to the right. From `4cm` to `5.5cm`
Original code:
```
\node[anchor=north] at (4cm,-3.25cm){\color{white}\fontsize{220}{100}\sffamily\bfseries\thepart}; 
```
Updated one:
```
\node[anchor=north] at (5.5cm,-3.25cm){\color{white}\fontsize{220}{100}\sffamily\bfseries\thepart}; 
```

Narrow down the width of the box containing the text. From `15cm` to `8cm`
Original code:
```
\node[anchor=north east] at (\paperwidth-1.5cm,-3.25cm){\parbox[t][][t]{15cm}{\strut\raggedleft\color{white}\fontsize{30}{30}\sffamily\bfseries#2}};
```
Updated one:
```
\node[anchor=north east] at (\paperwidth-1.5cm,-3.25cm){\parbox[t][][t]{8cm}{\strut\raggedleft\color{white}\fontsize{30}{30}\sffamily\bfseries#2}};
```

**Preview**
Before:
![image](https://github.com/PIX3LFLUX/HSK-Latex-Skript-Template/assets/20220723/4a6ed2be-4500-40b9-8e15-505f60f2cf66)

After:
![image](https://github.com/PIX3LFLUX/HSK-Latex-Skript-Template/assets/20220723/4faef920-1637-4b21-b2c0-d0c59e8c664e)
